source 'https://rubygems.org'

gem 'rails', '~> 5.0.0'

gem 'pg', '~> 0.18'
gem 'puma', '~> 3.0'

# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'

gem 'active_model_serializers', '~> 0.10.0'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'awesome_print'
  gem 'rspec-rails', '~> 3.5'
  gem 'factory_girl_rails'
  gem 'database_cleaner'
end

group :development do
  gem 'listen', '~> 3.0.5'
end

